import React from 'react';
import { StyleSheet, View, Text } from 'react-native';

export const Header = () => {
    return (
        <View style={[styles.container, styles.header]}>
            <View style={[styles.frame6054]}>

            </View>
        </View>
    );
};

export const Footer = () => {
    return (
        <View style={[styles.container, styles.footer]}>
            <Text style={styles.text}>Contents</Text>
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        height: 169.8,
    },
    header: {
        flex: 0,
        width: 167.5,
        height: 169.8,
        order: 0,
        alignSelf: 'stretch',
        flexGrow: 0,
    },
    frame6054: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        padding: 0,
        gap: 4.25,
        width: 62.98,
        height: 18,
        left: 96,
        top: 8.58,
    },
    numbermenuItem: {
        flex: 0,
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 4.24505,
        paddingRight: 8.49011,
        paddingLeft: 8.49011,
        paddingBottom: 4.24505,
        gap: 8,
        width: 62.98,
        height: 18,
        backgroundColor: 'gray',
        borderTopLeftRadius: 11.8862,
        borderTopRightRadius: 11.8862,
        borderBottomRightRadius: 11.8862,
        borderBottomLeftRadius: 11.8862,
        order: 0,
        flexGrow: 0,
    },
    possiblemenuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 3,
        paddingRight: 10,
        paddingLeft: 10,
        paddingBottom: 3,
        gap: 8,
        width: 56,
        height: 18,
        left: 103,
        top: 31,
        backgroundColor: '#FF7864',
        borderTopLeftRadius: 14,
        borderTopRightRadius: 14,
        borderBottomRightRadius: 14,
        borderBottomLeftRadius: 14,
    },
    possiblelabelText: {
        flex: 0,
        width: 36,
        height: 12,
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: 10,
        lineHeight: 12,
        letterSpacing: -0.408,
        color:'#FFFFFF',
        order: 0,
        flexGrow: 0,
    },
    calendarTime: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 3,
        gap: 3,
        width: 109,
        height: 21,
        right: 8.5,
        backgroundColor: 'gray',
        borderTopLeftRadius: 6,
        borderTopRightRadius: 6,
        borderBottomRightRadius: 6,
        borderBottomLeftRadius: 6,
        order: 0,
        flexGrow: 0,
    },
    footer: {
        flex: 0,
        backgroundColor: 'white',
        flexDirection: 'column',
        alignItems: 'flex-start',
        padding: 8,
        gap: 8,
        width: 167.5,
        height: 59.09,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderTopRightRadius: 24,
        borderBottomLeftRadius: 24,
        order: 1,
        alignSelf: 'stretch',
        flexGrow: 0,
    },
    body: {
        flex: 0,
        flexDirection: 'column',
        alignItems: 'flex-start',
        padding: 0,
        gap: 28.02,
        width: 151.5,
        height: 43.09,
        order: 0,
        alignSelf: 'stretch',
        flexGrow: 0,
    },
    content: {
        flex: 0,
        flexDirection: 'row',
        alignItems: 'center',
        padding: 0,
        gap: 13,
        width: 151.5,
        height: 43.09,
        order: 0,
        alignSelf: 'stretch',
        flexGrow: 0,
    }
    textBox: {
        flex: 0,
        flexDirection: 'column',
        alignItems: 'flex-start',
        padding: 0,
        gap: 8,
        width: 151.5,
        height: 43.09,
        order: 0,
        flexGrow: 1,
    },
    habitText: {
        flex: 0,
        width: 151.5,
        height: 17,
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: 13,
        lineHeight: 17,
        alignItems: 'center',
        letterSpacing: -0.04,
        color:'#000000',
        order: 0,
        alignSelf: 'stretch',
        flexGrow: 0,
    },
    frame6062: {
        flex: 0,
        flexDirection: 'row',
        alignItems: 'flex-start',
        padding: 0,
        gap: 1.7,
        width: 86.98,
        height: 18.09,
        order: 1,
        flexGrow: 0,
    },
    menuItem: {
        flex: 0,
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 2.54703,
        paddingRight: 8.49011,
        paddingLeft: 8.49011,
        paddingBottom: 2.54703,
        gap: 8,
        width: 86.98,
        height: 18.09,
        backgroundColor: 'pink',
        borderTopLeftRadius: 11.8862,
        borderTopRightRadius: 11.8862,
        borderBottomRightRadius: 11.8862,
        borderBottomLeftRadius: 11.8862,
        order: 0,
        flexGrow: 0,
    },
    labelText: {
        flex: 0,
        width: 70,
        height: 13,
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: 10,
        lineHeight: 13,
        letterSpacing: -0.346396,
        color:'#000000',
        order: 0,
        flexGrow: 0,
    },
});